version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app

  frontend:
    build: .
      # args:
      #   - SECRET_KEY=${SECRET_KEY}
      #   - NODE_ENV=${NODE_ENV}
    env_file: ./.env    
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - backend